import {test,expect} from '@playwright/test';import fs from 'node:fs/promises';import sharp from 'sharp';import {parse} from 'yaml';import {travelSchema} from '../../src/content/schema.mjs';
const base='http://127.0.0.1:4175/mikamika/';
async function hoverState(p,code){const d=await(await p.request.get(base+'data.json')).json(),a=d.map.find(s=>s.code===code).anchor,r=await p.locator('#travel-map').boundingBox(),v=await p.locator('#travel-map').evaluate(e=>({x:e.viewBox.baseVal.x,y:e.viewBox.baseVal.y,width:e.viewBox.baseVal.width,height:e.viewBox.baseVal.height})),scale=Math.min(r.width/v.width,r.height/v.height);await p.mouse.move(r.x+(r.width-v.width*scale)/2+(a[0]-v.x)*scale,r.y+(r.height-v.height*scale)/2+(a[1]-v.y)*scale);}
const ca=p=>p.locator('#travel-map [data-state="CA"]');const nj=p=>p.locator('#travel-map [data-state="NJ"]');
async function ready(p,url=base){const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await expect(p.locator('#state-select option')).toHaveCount(52);await expect(p.locator('#travel-map [data-state]')).toHaveCount(51);expect(errors).toEqual([]);}
test('hover, bubble tolerance, pinning, switching and keyboard focus restoration',async({page:p})=>{await ready(p);await hoverState(p,'CA');await expect(p.locator('#bubble')).toBeVisible();await expect(p.locator('#bubble h2')).toHaveText('California');await p.locator('#bubble').hover();await p.waitForTimeout(300);await expect(p.locator('#bubble')).toBeVisible();await ca(p).click();await hoverState(p,'NJ');await p.waitForTimeout(200);await expect(p.locator('#bubble h2')).toHaveText('California');await nj(p).focus();await p.keyboard.press('Enter');await expect(p.locator('#bubble h2')).toHaveText('New Jersey');await p.keyboard.press('Escape');await expect(p.locator('#bubble')).toBeHidden();await expect(nj(p)).toBeFocused();await ca(p).focus();await p.keyboard.press('Enter');await expect(p.locator('#bubble h2')).toHaveText('California');});
test('rapid hover cancels old preview; manual interaction pauses demo',async({page:p})=>{await ready(p);await hoverState(p,'CA');await hoverState(p,'NJ');await expect(p.locator('#bubble h2')).toHaveText('New Jersey');await p.locator('.journal-header').hover();await expect(p.locator('#bubble')).toBeHidden();await p.waitForTimeout(4000);await expect(p.locator('#bubble')).toBeHidden();});
test('album, lightbox navigation, Escape and stable hash restore',async({page:p})=>{await ready(p);await ca(p).click();await p.locator('#open-album').click();await expect(p.locator('#album')).toBeVisible();await expect(p).toHaveURL(/#state=CA$/);await expect(p.locator('#album-grid button')).toHaveCount(3);await p.locator('#album-grid button').first().click();await expect(p.locator('#lightbox')).toBeVisible();await p.keyboard.press('ArrowRight');await expect(p.locator('#photo-counter')).toHaveText('2 / 3');await p.keyboard.press('Escape');await expect(p.locator('#album-grid button').nth(1)).toBeFocused();await p.reload();await expect(p.locator('#album')).toBeVisible();await p.keyboard.press('Escape');await expect(p.locator('#album')).toBeHidden();await expect(p.locator('#state-select')).toBeFocused();});
test('production empty state never presents fake album',async({page:p})=>{await ready(p,'http://127.0.0.1:4176/mikamika/');await p.locator('#state-select').selectOption('CA');await expect(p.locator('#bubble')).toBeVisible();await expect(p.locator('#no-photos')).toBeVisible();await expect(p.locator('#open-album')).toBeHidden();await p.locator('#state-select').selectOption('FL');await expect(p.locator('#bubble')).toBeHidden();await expect(p.locator('#state-note')).toContainText('Not visited yet');await expect(p.locator('#scene>svg')).toContainText('');const data=await(await p.request.get('http://127.0.0.1:4176/mikamika/data.json')).json();expect(data.manifest.visited).toBe(24);expect(data.manifest.states.flatMap(s=>s.photos)).toEqual([]);});
for(const width of [1200,900,760,430,375])test(`layout fits ${width}px, dark theme and viewport collision`,async({page:p})=>{await p.setViewportSize({width,height:800});await ready(p);await p.locator('#theme').selectOption('dark');await expect(p.locator('html')).toHaveAttribute('data-theme','dark');await p.locator('#state-select').selectOption('CA');await expect(p.locator('#bubble')).toBeVisible();const rect=await p.locator('#bubble').boundingBox();expect(rect.x).toBeGreaterThanOrEqual(0);expect(rect.x+rect.width).toBeLessThanOrEqual(width);expect(rect.y+rect.height).toBeLessThanOrEqual(800);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width<=430){await p.locator('#photo-stack').click();await expect(p.locator('#album')).toBeVisible();}await expect(p.locator('#travel-map')).toBeVisible();await p.screenshot({path:`.test-output/pages-${width}-dark.png`});});
test('reduced motion is static and full introduction remains legible',async({page:p})=>{await p.emulateMedia({reducedMotion:'reduce'});await ready(p);await p.waitForTimeout(4200);await expect(p.locator('#bubble')).toBeHidden();await p.setContent(`<picture><source media="(prefers-reduced-motion: reduce)" srcset="${base}assets/readme/profile-light-static.svg"><img width="1200" src="${base}assets/readme/profile-light.svg"></picture>`);await expect(p.locator('img')).toHaveJSProperty('complete',true);expect(await p.locator('img').evaluate(e=>e.currentSrc)).toContain('-static.svg');});
test('script-free img plays multiple stages without changing its boundaries',async({page:p})=>{await p.goto(base+'image-test.html');await p.setContent(`<img id="profile" width="1200" src="${base}assets/readme/profile-light.svg">`);const img=p.locator('img');await img.evaluate(e=>e.decode());const bounds=await img.boundingBox();const shots=[];let previous=0;for(const [name,at] of [['start',1800],['enter',4200],['hold',6500],['collapse',10800],['idle',12500],['next-state',17500]]){await p.waitForTimeout(at-previous);previous=at;const bytes=await img.screenshot({path:`.test-output/img-${name}.png`});shots.push(await sharp(bytes).extract({left:845,top:30,width:270,height:192}).raw().toBuffer());expect(await img.boundingBox()).toEqual(bounds);}
 const diff=(a,b)=>a.reduce((n,x,i)=>n+Math.abs(x-b[i]),0)/a.length;expect(diff(shots[0],shots[2])).toBeGreaterThan(3);expect(diff(shots[2],shots[4])).toBeGreaterThan(3);expect(diff(shots[0],shots[4])).toBeLessThan(2);expect(diff(shots[2],shots[5])).toBeGreaterThan(1);
});
test('deterministic P1/P2 render under img, correct overlay extent and embedded photo clarity',async({page:p})=>{for(const name of ['p1-idle','p2-bubble']){await p.goto(base+'image-test.html');await p.setContent(`<img width="1200" src="${base}${name}.svg">`);await p.locator('img').evaluate(e=>e.decode());await p.locator('img').screenshot({path:`.test-output/${name}.png`});}const svg=await fs.readFile('.test-output/site/p2-bubble.svg','utf8');expect(svg).not.toMatch(/<script|foreignObject|\son\w+=/i);expect(svg).toContain('data:image/webp;base64,');expect(svg).toContain('id="bubble-CA" pointer-events="none" opacity="1" transform="translate(');expect(svg.indexOf('id="bubble-CA"')).toBeGreaterThan(svg.indexOf('click to explore'));});
test('editor imports, validates, previews cover/order and exports YAML',async({page:p})=>{await p.goto(base+'editor.html');await expect(p.locator('#edit-state option')).toHaveCount(51);await p.locator('#edit-state').selectOption('CA');await p.locator('#subtitle').fill('Updated local subtitle');await p.locator('#subtitle').blur();await expect(p.locator('#editor-status')).toContainText('Preview updated');const frame=p.frameLocator('#editor-preview');await expect(frame.locator('#bubble .subtitle')).toHaveText('Updated local subtitle');await p.locator('#photo-order').fill('测试 2.PNG\ncover.png');await p.locator('#photo-order').blur();await expect(frame.locator('#photo-stack img').last()).toHaveAttribute('alt',/测试 2.PNG/);const download=p.waitForEvent('download');await p.locator('#export-yaml').click();const file=await(await download).path();const config=travelSchema.parse(parse(await fs.readFile(file,'utf8')));expect(config.states.CA.subtitle).toBe('Updated local subtitle');expect(config.states.CA.preview_photos[0]).toBe('测试 2.PNG');expect(await p.locator('#editor-status').textContent()).not.toContain('saved to GitHub');await p.locator('#yaml-source').fill('schema_version: 999');await p.locator('#apply-yaml').click();await expect(p.locator('#editor-status')).toContainText('Invalid configuration');});
test('anchors are inside rendered state bodies (including AK, HI, RI)',async({page:p})=>{await ready(p);const data=await(await p.request.get(base+'data.json')).json();const results=await p.evaluate(shapes=>shapes.map(s=>{const el=document.querySelector(`#travel-map [data-state="${s.code}"]`);return el.isPointInFill(new DOMPoint(...s.anchor));}),data.map);expect(results.every(Boolean)).toBe(true);});

test('bubble translates between states while its tail geometry stays fixed',async({page:p})=>{await ready(p);await p.locator('#state-select').selectOption('CA');const a=await p.locator('#bubble').evaluate(e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,tail:getComputedStyle(e,'::after').left,blur:getComputedStyle(e).backdropFilter}));await p.locator('#state-select').selectOption('NJ');const b=await p.locator('#bubble').evaluate(e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,tail:getComputedStyle(e,'::after').left}));expect(b.x).toBeGreaterThan(a.x+100);expect(b.tail).toBe(a.tail);expect(a.blur).toContain('blur(9px)');});
test('confirmed visits include Arizona and count DC separately',async({page:p})=>{await ready(p,'http://127.0.0.1:4176/mikamika/');await expect(p.locator('.place-chip')).toHaveCount(25);await expect(p.locator('#state-count')).toHaveText('24 / 50');await p.locator('#state-select').selectOption('DC');await expect(p.locator('#bubble h2')).toHaveText('Washington, D.C.');await expect(p.locator('#bubble-category')).toHaveText('DISTRICT');await expect(p.locator('#no-photos')).toBeVisible();await p.locator('#state-select').selectOption('AZ');await expect(p.locator('#bubble h2')).toHaveText('Arizona');});
