import {test,expect} from '@playwright/test';import fs from 'node:fs/promises';import sharp from 'sharp';import {parse} from 'yaml';import {travelSchema} from '../../src/content/schema.mjs';
const base='http://127.0.0.1:4175/mikamika/';
async function hoverState(p,code){const d=await(await p.request.get(base+'data.json')).json(),a=d.map.find(s=>s.code===code).anchor,r=await p.locator('#travel-map').boundingBox(),v=await p.locator('#travel-map').evaluate(e=>({x:e.viewBox.baseVal.x,y:e.viewBox.baseVal.y,width:e.viewBox.baseVal.width,height:e.viewBox.baseVal.height})),scale=Math.min(r.width/v.width,r.height/v.height);await p.mouse.move(r.x+(r.width-v.width*scale)/2+(a[0]-v.x)*scale,r.y+(r.height-v.height*scale)/2+(a[1]-v.y)*scale);}
const ca=p=>p.locator('#travel-map [data-state="CA"]');const nj=p=>p.locator('#travel-map [data-state="NJ"]');
async function ready(p,url=base){const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await expect(p.locator('#state-select option')).toHaveCount(52);await expect(p.locator('#travel-map [data-state]')).toHaveCount(51);expect(errors).toEqual([]);}
test('hover, bubble tolerance, pinning, switching and keyboard focus restoration',async({page:p})=>{await ready(p);await hoverState(p,'CA');await expect(p.locator('#bubble')).toBeVisible();await expect(p.locator('#bubble h2')).toHaveText('California');await p.locator('#bubble').hover();await p.waitForTimeout(300);await expect(p.locator('#bubble')).toBeVisible();await ca(p).click();await hoverState(p,'NJ');await p.waitForTimeout(200);await expect(p.locator('#bubble h2')).toHaveText('California');await nj(p).focus();await p.keyboard.press('Enter');await expect(p.locator('#bubble h2')).toHaveText('New Jersey');await p.keyboard.press('Escape');await expect(p.locator('#bubble')).toBeHidden();await expect(nj(p)).toBeFocused();await ca(p).focus();await p.keyboard.press('Enter');await expect(p.locator('#bubble h2')).toHaveText('California');});
test('rapid hover cancels old preview; App stays idle until interaction',async({page:p})=>{await ready(p);await hoverState(p,'CA');await hoverState(p,'NJ');await expect(p.locator('#bubble h2')).toHaveText('New Jersey');await p.locator('.journal-header').hover();await expect(p.locator('#bubble')).toBeHidden();await p.clock.install();await p.clock.fastForward(70000);await expect(p.locator('#bubble')).toBeHidden();});
test('album, lightbox navigation, Escape and stable hash restore',async({page:p})=>{await ready(p);await ca(p).click();await p.locator('#open-album').click();await expect(p.locator('#album')).toBeVisible();await expect(p).toHaveURL(/#state=CA$/);await expect(p.locator('#album-grid button')).toHaveCount(3);await p.locator('#album-grid button').first().click();await expect(p.locator('#lightbox')).toBeVisible();await p.keyboard.press('ArrowRight');await expect(p.locator('#photo-counter')).toHaveText('2 / 3');await p.keyboard.press('Escape');await expect(p.locator('#album-grid button').nth(1)).toBeFocused();await p.reload();await expect(p.locator('#album')).toBeVisible();await p.keyboard.press('Escape');await expect(p.locator('#album')).toBeHidden();await expect(p.locator('#state-select')).toBeFocused();});
test('production visits and empty-photo behavior follow the published manifest',async({page:p})=>{const url='http://127.0.0.1:4176/mikamika/';await ready(p,url);const data=await(await p.request.get(url+'data.json')).json();const places=[...data.manifest.states,...data.manifest.regions],empty=places.find(s=>s.visited&&!s.photos.length),unvisited=places.find(s=>!s.visited);if(empty){await p.locator('#state-select').selectOption(empty.code);await expect(p.locator('#bubble')).toBeVisible();if(data.travel.preview.sample_photos_when_empty){await expect(p.locator('#photo-stack img')).toHaveCount(3);await expect(p.locator('#bubble-photo-count')).toHaveText('');await expect(p.locator('#open-album')).toBeVisible();}else{await expect(p.locator('#no-photos')).toBeVisible();await expect(p.locator('#open-album')).toBeHidden();}}if(unvisited){await p.locator('#state-select').selectOption(unvisited.code);await expect(p.locator('#bubble')).toBeHidden();await expect(p.locator('#state-note')).toContainText('Not visited yet');}expect(data.manifest.visited).toBe(data.manifest.states.filter(s=>s.visited).length);});
for(const width of [1200,900,760,430,375])test(`layout fits ${width}px, dark theme and viewport collision`,async({page:p})=>{await p.setViewportSize({width,height:800});await ready(p);await p.locator('#theme').selectOption('dark');await expect(p.locator('html')).toHaveAttribute('data-theme','dark');await p.locator('#state-select').selectOption('CA');await expect(p.locator('#bubble')).toBeVisible();const rect=await p.locator('#bubble').boundingBox();expect(rect.x).toBeGreaterThanOrEqual(0);expect(rect.x+rect.width).toBeLessThanOrEqual(width);expect(rect.y+rect.height).toBeLessThanOrEqual(800);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width<=430){await p.locator('#photo-stack').click();await expect(p.locator('#album')).toBeVisible();}await expect(p.locator('#travel-map')).toBeVisible();await p.screenshot({path:`.test-output/pages-${width}-dark.png`});});
test('reduced motion is static and full introduction remains legible',async({page:p})=>{await p.emulateMedia({reducedMotion:'reduce'});await ready(p);await p.waitForTimeout(4200);await expect(p.locator('#bubble')).toBeHidden();await p.setContent(`<picture><source media="(prefers-reduced-motion: reduce)" srcset="${base}assets/readme/profile-light-static.svg"><img width="1200" src="${base}assets/readme/profile-light.svg"></picture>`);await expect(p.locator('img')).toHaveJSProperty('complete',true);expect(await p.locator('img').evaluate(e=>e.currentSrc)).toContain('-static.svg');});
test('script-free img plays multiple stages without changing its boundaries',async({page:p})=>{await p.goto(base+'image-test.html');await p.setContent(`<img id="profile" width="1200" src="${base}assets/readme/profile-light.svg">`);const img=p.locator('img');await img.evaluate(e=>e.decode());const bounds=await img.boundingBox();const shots=[];const started=await p.evaluate(()=>performance.now());for(const [name,at] of [['start',1000],['hold',3000],['idle',5000],['next-state',7000]]){const elapsed=await p.evaluate(()=>performance.now())-started;await p.waitForTimeout(Math.max(0,at-elapsed));const bytes=await img.screenshot({path:`.test-output/img-${name}.png`});shots.push(await sharp(bytes).extract({left:820,top:75,width:235,height:270}).raw().toBuffer());expect(await img.boundingBox()).toEqual(bounds);}
 const diff=(a,b)=>a.reduce((n,x,i)=>n+Math.abs(x-b[i]),0)/a.length;expect(diff(shots[0],shots[1])).toBeGreaterThan(3);expect(diff(shots[1],shots[2])).toBeGreaterThan(3);expect(diff(shots[0],shots[2])).toBeLessThan(2);expect(diff(shots[1],shots[3])).toBeGreaterThan(1);
});
test('deterministic P1/P2 render under img, correct overlay extent and embedded photo clarity',async({page:p})=>{for(const name of ['p1-idle','p2-bubble']){await p.goto(base+'image-test.html');await p.setContent(`<img width="1200" src="${base}${name}.svg">`);await p.locator('img').evaluate(e=>e.decode());await p.locator('img').screenshot({path:`.test-output/${name}.png`});}const svg=await fs.readFile('.test-output/site/p2-bubble.svg','utf8');expect(svg).not.toMatch(/<script|foreignObject|\son\w+=/i);expect(svg).toContain('data:image/webp;base64,');expect(svg).toContain('id="bubble-CA" pointer-events="none" opacity="1" transform="translate(');expect(svg.indexOf('id="bubble-CA"')).toBeGreaterThan(svg.indexOf('click to explore'));});
test('editor imports, validates, previews cover/order and exports YAML',async({page:p})=>{await p.goto(base+'editor.html');await expect(p.locator('#edit-state option')).toHaveCount(51);await p.locator('#edit-state').selectOption('CA');await p.locator('#subtitle').fill('Updated local subtitle');await p.locator('#subtitle').blur();await expect(p.locator('#editor-status')).toContainText('Preview updated');const frame=p.frameLocator('#editor-preview');await expect(frame.locator('#bubble .subtitle')).toHaveText('Visited: Updated local subtitle');await p.locator('#photo-order').fill('测试 2.PNG\ncover.png');await p.locator('#photo-order').blur();await expect(frame.locator('#photo-stack img').last()).toHaveAttribute('alt',/测试 2.PNG/);const download=p.waitForEvent('download');await p.locator('#export-yaml').click();const file=await(await download).path();const config=travelSchema.parse(parse(await fs.readFile(file,'utf8')));expect(config.states.CA.subtitle).toBe('Updated local subtitle');expect(config.states.CA.preview_photos[0]).toBe('测试 2.PNG');expect(await p.locator('#editor-status').textContent()).not.toContain('saved to GitHub');await p.locator('#yaml-source').fill('schema_version: 999');await p.locator('#apply-yaml').click();await expect(p.locator('#editor-status')).toContainText('Invalid configuration');});
test('anchors are inside rendered state bodies (including AK, HI, RI)',async({page:p})=>{await ready(p);const data=await(await p.request.get(base+'data.json')).json();const results=await p.evaluate(shapes=>shapes.map(s=>{const el=document.querySelector(`#travel-map [data-state="${s.code}"]`);return el.isPointInFill(new DOMPoint(...s.anchor));}),data.map);expect(results.every(Boolean)).toBe(true);});

test('centered tail follows a state and hover location, then remains pinned',async({page:p})=>{await ready(p);await hoverState(p,'CA');await expect(p.locator('#bubble')).toBeVisible();await p.waitForTimeout(500);const a=await p.locator('#bubble').evaluate(e=>({x:parseFloat(e.style.left),tipX:+e.dataset.tipX,tipY:+e.dataset.tipY,baseX:+e.dataset.baseX,width:e.offsetWidth,clip:getComputedStyle(e,'::after').clipPath,blur:getComputedStyle(e).backdropFilter}));expect(a.baseX).toBe(a.width/2);await p.mouse.move(a.tipX+3,a.tipY+3);const moved=await p.locator('#bubble').evaluate(e=>({tipX:+e.dataset.tipX,tipY:+e.dataset.tipY}));expect(moved.tipX).toBeCloseTo(a.tipX+3,0);expect(moved.tipY).toBeCloseTo(a.tipY+3,0);await p.mouse.click(moved.tipX,moved.tipY);const pinnedTip=await p.locator('#bubble').evaluate(e=>+e.dataset.tipX);await hoverState(p,'NJ');expect(await p.locator('#bubble').evaluate(e=>+e.dataset.tipX)).toBe(pinnedTip);await p.locator('#state-select').selectOption('NJ');await p.waitForTimeout(500);const b=await p.locator('#bubble').evaluate(e=>({x:parseFloat(e.style.left),baseX:+e.dataset.baseX,width:e.offsetWidth}));expect(b.x).toBeGreaterThan(a.x+100);expect(b.baseX).toBe(b.width/2);expect(a.blur).toContain('blur(9px)');});
test('visited chips match the manifest and DC remains separate from the state count',async({page:p})=>{const url='http://127.0.0.1:4176/mikamika/';await ready(p,url);const data=await(await p.request.get(url+'data.json')).json(),places=[...data.manifest.states,...data.manifest.regions];await expect(p.locator('.place-chip')).toHaveCount(places.filter(s=>s.visited).length);await expect(p.locator('#state-count')).toHaveText(`${data.manifest.visited} / 50`);const dc=data.manifest.regions.find(s=>s.code==='DC');if(dc.visited){await p.locator('#state-select').selectOption('DC');await expect(p.locator('#bubble h2')).toHaveText(dc.title);await expect(p.locator('#bubble .subtitle')).toHaveText('Visited: '+(dc.subtitle||'—'));await expect(p.locator('#open-album')).toBeVisible({visible:!!dc.preview.length});}const az=data.manifest.states.find(s=>s.code==='AZ');if(az.visited){await p.locator('#state-select').selectOption('AZ');await expect(p.locator('#bubble h2')).toHaveText(az.title);}});

test('production hero, sample album, ellipsis and ordered stack',async({page:p})=>{const url='http://127.0.0.1:4176/mikamika/';await ready(p,url);const data=await(await p.request.get(url+'data.json')).json();await expect(p.locator('#journey-summary')).toHaveText(`${data.manifest.visited} / 50 states`);await expect(p.locator('.journal-kicker')).toHaveCount(0);await p.locator('#state-select').selectOption('CA');await expect(p.locator('#photo-stack img')).toHaveCount(3);await p.waitForTimeout(500);const layers=await p.locator('#photo-stack img').evaluateAll(imgs=>imgs.map(i=>({index:+i.dataset.index,x:i.getBoundingClientRect().x,y:i.getBoundingClientRect().y,width:i.getBoundingClientRect().width,rotate:getComputedStyle(i).rotate})).sort((a,b)=>a.index-b.index));expect(layers[1].x).toBeGreaterThan(layers[0].x);expect(layers[1].y).toBeGreaterThan(layers[0].y);expect(layers[2].x-layers[1].x).toBeCloseTo(layers[1].x-layers[0].x,0);expect(layers[2].width).toBeCloseTo(layers[0].width,1);expect(layers[2].rotate).toBe('0deg');const caPath=p.locator('#travel-map [data-state="CA"]');await caPath.focus();expect(await caPath.evaluate(e=>getComputedStyle(e).outlineStyle)).toBe('none');await p.evaluate(travel=>{travel.states.CA.subtitle='San Francisco, Los Angeles, Yosemite, coastal roads, mountain parks, lake trails, museums, cafés, old streets, lookout points and many more places';window.postMessage({type:'mika-preview',travel,code:'CA'},location.origin);},data.travel);await expect(p.locator('#bubble .subtitle')).toContainText('Visited: San Francisco');expect(await p.locator('#bubble .subtitle').evaluate(e=>({clamp:getComputedStyle(e).webkitLineClamp,whiteSpace:getComputedStyle(e).whiteSpace}))).toEqual({clamp:'2',whiteSpace:'normal'});await p.locator('#open-album').click();await expect(p.locator('#album .section-kicker')).toHaveText('PHOTO ALBUM');await expect(p.locator('#album-grid button')).toHaveCount(3);await p.setContent(await fs.readFile('.test-output/site/p2-bubble.svg','utf8'));const label=p.locator('#bubble-CA g[aria-label^="Visited:"]');expect(await label.getAttribute('aria-label')).toMatch(/\.\.\.$/);expect(await label.evaluate(e=>e.getBBox().width)).toBeLessThanOrEqual(data.layout.boxes.bubble[2]-24);});

test('App never opens an idle bubble and eastern state tips stay anchored',async({page:p})=>{await p.clock.install();await ready(p);await p.clock.fastForward(75000);await expect(p.locator('#bubble')).toBeHidden();const data=await(await p.request.get(base+'data.json')).json();for(const code of ['NJ','NY','RI']){await p.locator('#state-select').selectOption(code);await p.clock.fastForward(500);await expect(p.locator('#bubble')).toBeVisible();const g=await p.locator('#bubble').evaluate(e=>({left:parseFloat(e.style.left),top:parseFloat(e.style.top),w:e.offsetWidth,h:e.offsetHeight,tipX:+e.dataset.tipX,tipY:+e.dataset.tipY,tail:parseFloat(e.style.getPropertyValue('--tail-height')),clip:e.style.getPropertyValue('--tail-clip')}));const anchor=await p.locator('#travel-map').evaluate((svg,a)=>{const pt=new DOMPoint(...a).matrixTransform(svg.getScreenCTM());return [pt.x,pt.y];},data.map.find(s=>s.code===code).anchor);expect(g.left+g.w).toBeLessThanOrEqual(1232);expect(g.tipX,JSON.stringify({code,g,anchor})).toBeCloseTo(anchor[0],1);expect(g.top+g.h+g.tail).toBeCloseTo(anchor[1],1);expect(g.clip).toContain('polygon(');}});

test('production SVG displays every visited place once during a complete cycle',async({page:p})=>{
 const url='http://127.0.0.1:4176/mikamika/',data=await(await p.request.get(url+'data.json')).json(),svg=await(await p.request.get(url+'assets/readme/profile-light.svg')).text();
 const visited=[...data.manifest.states,...data.manifest.regions].filter(s=>s.visited).map(s=>s.code);expect(visited).toHaveLength(26);
 await p.setContent(svg);const result=await p.evaluate(({visited,preview})=>{
 const animations=document.getAnimations();for(const a of animations)a.pause();
 const seen=[];for(let i=0;i<visited.length;i++){for(const a of animations)a.currentTime=preview.initial_idle_ms+i*preview.state_cycle_ms+1000;const visible=visited.filter(code=>+getComputedStyle(document.getElementById('bubble-'+code)).opacity>.99);seen.push(visible);}
 for(const a of animations)a.currentTime=preview.initial_idle_ms+visited.length*preview.state_cycle_ms+1000;const repeat=visited.filter(code=>+getComputedStyle(document.getElementById('bubble-'+code)).opacity>.99);
 return {seen,repeat};},{visited,preview:data.travel.preview});
 expect(result.seen.every(a=>a.length===1)).toBe(true);expect(result.seen.flat().sort()).toEqual([...visited].sort());expect(result.repeat).toEqual(result.seen[0]);
});
