import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import sharp from 'sharp';import {parse} from 'yaml';
import {bubblePlacement} from '../src/render/placement.mjs';import {spring} from '../src/render/motion.mjs';
import {addSamplePreviews} from '../src/content/samples.mjs';
import {travelSchema} from '../src/content/schema.mjs';import {scanPhotos} from '../src/content/photos.mjs';import {STATES} from '../src/content/states.mjs';import {frameAt,selectPreviews} from '../src/render/timeline.mjs';import {buildMap} from '../src/render/map.mjs';
const config=()=>{const c=travelSchema.parse(parse(requireText));c.states={};c.regions={};return c;};const requireText=await fs.readFile('content/travel.yaml','utf8');
async function setup(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mika-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.mkdir(path.join(dir,'photos/A/CA'),{recursive:true});return {dir,root:path.join(dir,'photos'),out:path.join(dir,'out'),cache:path.join(dir,'cache')};}
const fixture=await fs.readFile('tests/fixtures/landscape.png');
test('all fifty codes and directories are unique',async()=>{assert.equal(STATES.length,50);assert.equal(new Set(STATES.map(s=>s.code)).size,50);for(const s of STATES)await fs.access(`photos/${s.group}/${s.code}/.gitkeep`);});
test('schema rejects unknown states, paths, timing overlaps and invalid focus',()=>{for(const patch of [{states:{XX:{visited:true}}},{states:{CA:{cover:'../x.jpg'}}},{states:{CA:{photo_focus:{'x.jpg':[1.2,0]}}}},{preview:{...config().preview,state_cycle_ms:100}}])assert.equal(travelSchema.safeParse({...config(),...patch}).success,false);});
test('empty photos produce fifty unvisited states, no preview',async t=>{const s=await setup(t),m=await scanPhotos(s.root,config(),s.out,{cache:s.cache});assert.equal(m.visited,0);assert.equal(selectPreviews(m,config().preview).length,0);});
test('explicit visited false prevents all photo publication',async t=>{const s=await setup(t);await fs.writeFile(path.join(s.root,'A/CA/cover.PNG'),fixture);const c=config();c.states.CA={visited:false};const m=await scanPhotos(s.root,c,s.out,{cache:s.cache});assert.equal(m.visited,0);assert.deepEqual(m.states.find(s=>s.code==='CA').photos,[]);assert.deepEqual(await fs.readdir(path.join(s.out,'photos')),[]);});
test('visited true needs no photograph',async t=>{const s=await setup(t),c=config();c.states.CA={visited:true};const m=await scanPhotos(s.root,c,s.out,{cache:s.cache});assert.equal(m.visited,1);assert.equal(selectPreviews(m,c.preview).length,0);});
test('one and two photos do not duplicate layers; cover and natural sorting support Unicode',async t=>{const s=await setup(t);for(const name of ['10 中文.PNG','2 中文.PNG','cover.PNG'])await fs.writeFile(path.join(s.root,'A/CA',name),fixture);const c=config();const m=await scanPhotos(s.root,c,s.out,{cache:s.cache}),state=m.states.find(s=>s.code==='CA');assert.equal(state.preview[0].name,'cover.PNG');assert.equal(state.preview[1].name,'2 中文.PNG');assert.equal(state.preview[2].name,'10 中文.PNG');await fs.unlink(path.join(s.root,'A/CA/cover.PNG'));await fs.unlink(path.join(s.root,'A/CA/10 中文.PNG'));const n=await scanPhotos(s.root,c,s.out,{cache:s.cache});assert.equal(n.states.find(s=>s.code==='CA').preview.length,1);});
test('config overrides cover, order, focus and visited inference',async t=>{const s=await setup(t);for(const name of ['2.png','3.png','cover.png'])await fs.writeFile(path.join(s.root,'A/CA',name),fixture);const c=config();c.states.CA={cover:'3.png',preview_photos:['2.png','3.png'],photo_focus:{'2.png':[.1,.9]},color:'#123456',subtitle:'Long subtitle'};const m=await scanPhotos(s.root,c,s.out,{cache:s.cache}),state=m.states.find(s=>s.code==='CA');assert.equal(state.preview[0].name,'2.png');assert.equal(state.color,'#123456');assert.equal(state.subtitle,'Long subtitle');assert.notEqual(state.photos[0].thumb,state.photos[1].thumb);c.map.infer_visited_from_photos=false;const n=await scanPhotos(s.root,c,s.out,{cache:s.cache});assert.equal(n.visited,0);assert.deepEqual(await fs.readdir(path.join(s.out,'photos')),[]);});
test('invalid files are reported while valid images survive',async t=>{const s=await setup(t);await fs.writeFile(path.join(s.root,'A/CA/bad.jpg'),'invalid');await fs.writeFile(path.join(s.root,'A/CA/ok.png'),fixture);await fs.writeFile(path.join(s.root,'A/CA/not-photo.svg'),'<script/>');const m=await scanPhotos(s.root,config(),s.out,{cache:s.cache});assert.equal(m.visited,1);assert.match(m.warnings.join(' '),/Invalid image skipped: CA\/bad.jpg/);assert.equal(m.states.find(s=>s.code==='CA').photos.length,1);});
test('JPEG, PNG and WebP decode; orientation and metadata are normalized',async t=>{const s=await setup(t);for(const format of ['jpeg','png','webp'])await sharp(fixture).toFormat(format).toFile(path.join(s.root,'A/CA',`photo.${format}`));await sharp(fixture).withMetadata({orientation:6}).jpeg().toFile(path.join(s.root,'A/CA/orient.jpg'));const m=await scanPhotos(s.root,config(),s.out,{cache:s.cache}),files=m.states.find(s=>s.code==='CA').photos;assert.equal(files.length,4);for(const f of files){const info=await sharp(path.join(s.out,f.src)).metadata();assert.equal(info.exif,undefined);assert.equal(info.orientation,undefined);}const f=files.find(f=>f.name==='orient.jpg'),meta=await sharp(path.join(s.out,f.src)).metadata();assert.equal(meta.width,90);assert.equal(meta.height,140);});
test('replacement and deletion invalidate cache and outputs',async t=>{const s=await setup(t),file=path.join(s.root,'A/CA/x.png');await fs.writeFile(file,fixture);const a=await scanPhotos(s.root,config(),s.out,{cache:s.cache});await sharp(fixture).modulate({hue:90}).toFile(file);const b=await scanPhotos(s.root,config(),s.out,{cache:s.cache});assert.notEqual(a.states[4].photos[0].src,b.states[4].photos[0].src);assert.equal((await fs.readdir(path.join(s.out,'photos'))).length,2);await fs.unlink(file);const c=await scanPhotos(s.root,config(),s.out,{cache:s.cache});assert.equal(c.visited,0);assert.deepEqual(await fs.readdir(path.join(s.out,'photos')),[]);});
test('state identity follows directory code; duplicates fail deterministically',async t=>{const s=await setup(t);await fs.writeFile(path.join(s.root,'A/CA/x.png'),fixture);await fs.mkdir(path.join(s.root,'B'));await fs.rename(path.join(s.root,'A/CA'),path.join(s.root,'B/CA'));assert.equal((await scanPhotos(s.root,config(),s.out,{cache:s.cache})).visited,1);await fs.mkdir(path.join(s.root,'A/CA'));await assert.rejects(scanPhotos(s.root,config(),s.out,{cache:s.cache}),/Duplicate state directories: CA/);});
test('out-of-root file and directory symlinks are blocked',async t=>{const s=await setup(t);await fs.writeFile(path.join(s.dir,'secret.png'),fixture);await fs.symlink(path.join(s.dir,'secret.png'),path.join(s.root,'A/CA/link.png'));await assert.rejects(scanPhotos(s.root,config(),s.out,{cache:s.cache}),/escapes photos root/);});
test('two-second bubble retracts for two seconds and advances to the next state',()=>{const p=config().preview,a=[{code:'CA'},{code:'NJ'}],start=p.initial_idle_ms;assert.equal(frameAt(start-1,p,a).state,null);assert.equal(frameAt(start+500,p,a).state.code,'CA');assert.equal(frameAt(start+500,p,a).opacity,1);assert.equal(frameAt(start+2000,p,a).opacity,0);assert.equal(frameAt(start+3999,p,a).opacity,0);assert.equal(frameAt(start+4500,p,a).state.code,'NJ');assert.equal(frameAt(start+4500,p,a).opacity,1);assert.equal(frameAt(0,p,[]).state,null);});
test('preview limits do not remove visits; daily selection rotates',()=>{const p={...config().preview,max_states:6},m={states:STATES.map(s=>({...s,visited:true,preview_enabled:true,preview:[{}]}))};const a=selectPreviews(m,p,'2026-10-06'),b=selectPreviews(m,{...p,selection:'daily'},'2026-10-06'),c=selectPreviews(m,{...p,selection:'daily'},'2026-10-07');assert.equal(a.length,6);assert.equal(m.states.length,50);assert.notEqual(b[0].code,c[0].code);assert.equal(selectPreviews(m,{...p,order:['TX']})[0].code,'TX');});
test('map has fifty unique IDs; AK/HI use insets; all anchors lie inside visible polygons',async()=>{const l=JSON.parse(await fs.readFile('content/layout.json'));const map=buildMap(l);assert.equal(map.length,50);assert.equal(new Set(map.map(s=>s.code)).size,50);for(const s of map){assert.ok(s.path.startsWith('M'));const [[x,y],[x2,y2]]=s.bounds;assert.ok(s.anchor[0]>=x&&s.anchor[0]<=x2&&s.anchor[1]>=y&&s.anchor[1]<=y2);}assert.ok(map.find(s=>s.code==='AK').anchor[1]>map.find(s=>s.code==='CA').anchor[1]);});

test('DC supports visits and photos without increasing the fifty-state count',async t=>{const s=await setup(t);await fs.mkdir(path.join(s.root,'Eastern/DC'),{recursive:true});await fs.writeFile(path.join(s.root,'Eastern/DC/cover.png'),fixture);const c=config();c.states.AZ={visited:true};c.regions.DC={visited:true};c.preview.order=['DC'];const m=await scanPhotos(s.root,c,s.out,{cache:s.cache});assert.equal(m.visited,1);assert.equal(m.states.length,50);assert.equal(m.regions[0].code,'DC');assert.equal(m.regions[0].photos.length,1);assert.equal(selectPreviews(m,c.preview)[0].code,'DC');});

test('three sample previews serve visited empty states without inventing photos or visits',async t=>{const s=await setup(t),c=config();c.states.CA={visited:true};c.states.PA={visited:true};const m=await scanPhotos(s.root,c,s.out,{cache:s.cache});await addSamplePreviews(m,c,s.out);assert.equal(m.visited,2);assert.equal(m.states.find(s=>s.code==='CA').photos.length,0);assert.equal(m.states.find(s=>s.code==='CA').preview.length,3);assert.ok(m.states.find(s=>s.code==='CA').preview.every(f=>f.sample));assert.equal(m.states.find(s=>s.code==='FL').preview.length,0);assert.equal(m.sample_photos.length,3);await fs.writeFile(path.join(s.root,'A/CA/real.png'),fixture);const real=await scanPhotos(s.root,c,s.out,{cache:s.cache});await addSamplePreviews(real,c,s.out);assert.equal(real.states.find(s=>s.code==='CA').preview.length,1);assert.ok(!real.states.find(s=>s.code==='CA').preview[0].sample);});

test('centered tail base targets every state while the body fits the README',async()=>{const layout=JSON.parse(await fs.readFile('content/layout.json'));for(const shape of buildMap(layout,{includeRegions:true})){const p=bubblePlacement(shape.anchor,layout),[,,rawW,rawH]=layout.boxes.bubble,w=rawW*(layout.bubble.scale??1),h=rawH*(layout.bubble.scale??1);assert.equal(p.baseX,w/2);assert.ok(p.x>=8&&p.x+w<=1192);assert.ok(p.y>=8);assert.equal(p.x+p.tipX,shape.anchor[0]);assert.equal(p.y+p.tipY,shape.anchor[1]);assert.ok(p.tipY>h);}});
test('shared spring settles without overshooting and accelerates then decelerates',()=>{assert.equal(spring(0),0);assert.equal(spring(1),1);let previous=0;for(let i=1;i<=100;i++){const value=spring(i/100);assert.ok(value>=previous&&value<=1);previous=value;}assert.ok(spring(.5)>.8);assert.ok(spring(.02)-spring(0)<spring(.12)-spring(.1));});

test('published preview cycles through all 25 visited states and DC before repeating',()=>{
 const c=travelSchema.parse(parse(requireText)),manifest={states:STATES.map(s=>({...s,visited:c.states[s.code]?.visited===true,preview_enabled:c.states[s.code]?.preview_enabled!==false,preview:[{}]})),regions:[{code:'DC',visited:c.regions.DC.visited,preview_enabled:true,preview:[{}]}]},selected=selectPreviews(manifest,c.preview);
 const expected='AZ CA CO DE IA ID IL IN MA MD MI MN MT NE NJ NV NY OH PA SD UT VA WI WV WY DC'.split(' ');
 assert.deepEqual(selected.map(s=>s.code).sort(),expected.sort());
 const seen=[];for(let i=0;i<selected.length;i++){const f=frameAt(c.preview.initial_idle_ms+i*c.preview.state_cycle_ms+1000,c.preview,selected);assert.equal(f.opacity,1);seen.push(f.state.code);}
 assert.equal(new Set(seen).size,26);assert.deepEqual(seen,selected.map(s=>s.code));assert.equal(frameAt(c.preview.initial_idle_ms+selected.length*c.preview.state_cycle_ms+1000,c.preview,selected).state.code,seen[0]);
});
