import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {dateInZone,streakFromDays,graphql,fetchStats,emptyStats} from '../src/data/github.mjs';import rank from '../vendor/calculateRank.js';
const days=(...dates)=>dates.map(date=>({date,contributionCount:1}));
test('today/yesterday continuation and gaps',()=>{assert.equal(streakFromDays(days('2025-12-31','2026-01-01'),'2026-01-02').count,2);assert.equal(streakFromDays(days('2025-12-31','2026-01-01','2026-01-02'),'2026-01-02').count,3);assert.equal(streakFromDays(days('2026-01-01'),'2026-01-03').count,0);assert.equal(streakFromDays([],'2026-01-02').start,null);});
test('streak date uses configured timezone across UTC midnight',()=>{assert.equal(dateInZone(new Date('2026-01-02T02:00:00Z'),'America/Los_Angeles'),'2026-01-01');assert.equal(dateInZone(new Date('2026-01-02T02:00:00Z'),'UTC'),'2026-01-02');});
test('API errors, missing token and partial responses are rejected without exposing token',async()=>{await assert.rejects(graphql('',{},{}),/credential/);for(const body of [{errors:[{message:'secret'}],data:{user:{}}},{data:null}])await assert.rejects(graphql('',{},{token:'SECRET',fetcher:async()=>({ok:true,json:async()=>body})}),e=>!e.message.includes('SECRET')&&!e.message.includes('secret'));await assert.rejects(graphql('',{},{token:'SECRET',fetcher:async()=>({ok:false,status:401})}),/401/);});
test('rate limit exhaustion rejected',async()=>{await assert.rejects(graphql('',{},{token:'x',fetcher:async()=>({ok:true,json:async()=>({data:{user:{},rateLimit:{remaining:0}}})})}),/rate limit/);});
test('rank is computed from metrics and changes with data',()=>{const params={all_commits:false,commits:0,prs:0,issues:0,reviews:0,stars:0,followers:0};assert.equal(rank(params).level,'C');assert.notEqual(rank({...params,stars:1000,prs:1000,commits:5000}).level,'C');assert.equal(emptyStats().stars,null);});
test('pagination, all-time calendars, cache reuse and last-known-good fallback',async t=>{const cache=await fs.mkdtemp(path.join(os.tmpdir(),'mika-stats-'));t.after(()=>fs.rm(cache,{recursive:true,force:true}));let repoCalls=0,calendarCalls=0;
 const fetcher=async(url,opts)=>{const {query,variables:v}=JSON.parse(opts.body);let user;
  if(query.includes('contributionCalendar')){calendarCalls++;const ds=[];for(let time=Date.parse(v.from.slice(0,10)+'T12:00:00Z');time<=Date.parse(v.to.slice(0,10)+'T12:00:00Z');time+=86400000)ds.push({date:new Date(time).toISOString().slice(0,10),contributionCount:1});user={contributionsCollection:{contributionCalendar:{weeks:[{contributionDays:ds}]}}};}
  else if(v.after){repoCalls++;user={repositories:{nodes:[{stargazerCount:7}],pageInfo:{hasNextPage:false,endCursor:null}}};}
  else user={createdAt:'2025-12-30T00:00:00Z',followers:{totalCount:1},pullRequests:{totalCount:42},openIssues:{totalCount:2},closedIssues:{totalCount:4},repositoriesContributedTo:{totalCount:5},contributionsCollection:{totalCommitContributions:3,totalPullRequestReviewContributions:1},repositories:{nodes:[{stargazerCount:5}],pageInfo:{hasNextPage:true,endCursor:'next'}}};
  return {ok:true,json:async()=>({data:{user,rateLimit:{remaining:100}}})};};
 const opts={token:'x',cache,fetcher,now:new Date('2026-01-02T20:00:00Z')},profile={username:'fixture-test',stats_timezone:'America/Los_Angeles'};
 const a=await fetchStats(profile,opts);assert.equal(a.stars,12);assert.equal(a.prs,42);assert.equal(a.total,4);assert.equal(repoCalls,1);assert.equal(calendarCalls,2);assert.equal(a.streak.count,4);
 const b=await fetchStats(profile,opts);assert.equal(b.total,4);assert.equal(calendarCalls,3);
 const c=await fetchStats(profile,{...opts,fetcher:async()=>({ok:false,status:401})});assert.equal(c.status,'stale');assert.equal(c.stars,12);assert.equal(c.fetched_at,a.fetched_at);
});
test('first failure never substitutes another account or zero values',async t=>{const cache=await fs.mkdtemp(path.join(os.tmpdir(),'mika-first-'));t.after(()=>fs.rm(cache,{recursive:true,force:true}));const s=await fetchStats({username:'no-snapshot-test',stats_timezone:'UTC'},{cache,token:'bad',fetcher:async()=>({ok:false,status:401})});assert.equal(s.status,'unavailable');assert.equal(s.stars,null);assert.equal(s.total,null);});
