import fs from 'node:fs';
import {icons} from '../../vendor/github-readme-stats-icons.mjs';
import {text,esc,ellipsis} from './text.mjs';
import {bubbleOrigin} from './placement.mjs';
import {frameAt,selectPreviews,layerSpread} from './timeline.mjs';
const palettes={light:{bg:'#FFFCFE',card:'#FFF7FB',border:'#F2E4F0',ink:'#625B70',muted:'#9496AA',pink:'#B85C8A',purple:'#9B7BE8',track:'#E7D0DF',bubble:'#F4EAFB'},dark:{bg:'#16131D',card:'#211B2B',border:'#3B2B47',ink:'#E8E1EE',muted:'#B0A5BC',pink:'#EEA1C4',purple:'#BCA5FF',track:'#533B54',bubble:'#362944'}};
function smil(attr,values,keys,dur){return `<animate attributeName="${attr}" values="${values.join(';')}" keyTimes="${keys.join(';')}" dur="${dur}ms" repeatCount="indefinite"/>`;}
function transformed(values,keys,dur){return `<animateTransform attributeName="transform" type="translate" values="${values.map(v=>v.join(' ')).join(';')}" keyTimes="${keys.join(';')}" dur="${dur}ms" repeatCount="indefinite"/>`;}
const fmtDate=d=>d?new Date(d.slice(0,10)+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}):'—';
const fmtShort=d=>d?new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'}):'—';
const value=n=>n==null?'—':n.toLocaleString('en-US');
function card([x,y,w,h],p){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="16" fill="${p.card}" stroke="${p.border}"/>`;}
function cloudAsset(theme){const source=fs.readFileSync(new URL(`../../assets/source/mika-about-${theme}.svg`,import.meta.url),'utf8');
 return source.slice(source.indexOf('<g transform="translate(35'),source.indexOf('<!-- ambient pixels')).replace(/<animateTransform[\s\S]*?\/>/g,'').replace(/url\(#cloudSoft\)/g,'url(#scene-cloudSoft)').replace('translate(35, 0)','translate(0, 0)').replace('translate(1043, 78)','translate(0, 0)');}
function clouds(theme,l,animated){let source=cloudAsset(theme);const marker=source.indexOf('<g transform="translate(0, 0)">',10);const pieces=[source.slice(0,marker),source.slice(marker)];return ['left','right'].map((key,i)=>{const [x,y,s]=l.clouds[key];return `<g transform="translate(${x} ${y}) scale(${s})"><g>${animated?transformed([[0,0],[2,-3],[0,0],[-2,2],[0,0]],[0,.25,.5,.75,1],i?5800:4900):''}${pieces[i]}</g></g>`;}).join('');}
function icon(i,x,y,p){return `<g transform="translate(${x} ${y})" fill="${p.purple}">${icons[['star','commits','prs','issues','contribs'][i]]}</g>`;}
function rankRing(cx,cy,r,rank,p){return `<circle cx="${cx}" cy="${cy}" r="${r}" stroke="${p.track}" stroke-width="5" fill="none"/><circle cx="${cx}" cy="${cy}" r="${r}" stroke="${p.pink}" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="${2*Math.PI*r*(rank?1-rank.percentile/100:0)} ${2*Math.PI*r}" transform="rotate(-90 ${cx} ${cy})"/>${text(rank?.level??'—',cx,cy+12,28,p.ink,{anchor:'middle',weight:700,family:'arimo'})}`;}
export function renderBubble(state,l,theme,{spread=1,opacity=1,lift=0,scale=1,id=state.code,animate='',imageHref=f=>f.dataURI,t,phases}={}){
 const p=palettes[theme],[bx,by,w,h]=l.boxes.bubble,[x,y]=bubbleOrigin(state.anchor,l),[px,py,pw,ph]=l.bubble.photo;
 const titleSize=Math.min(l.bubble.title_size, l.bubble.title_size*(w-36)/Math.max(1,(state.title.length*8)));
 let photos='';for(let i=state.preview.length-1;i>=0;i--){const layer=t!=null&&phases?layerSpread(t,phases,i):spread;const f=state.preview[i],[dx,dy]=l.bubble.offsets[i]??[75,22],factor=1-i*.035;const photoId=`photo-${id}-${i}`;
 photos+=`<g transform="translate(${px+dx*layer} ${py+dy*layer})"><g transform="scale(${factor}) rotate(${i?i*.8*layer:0} ${pw/2} ${ph/2})" opacity="${i===0?1:i===1?.87:.72}" ${i?`filter="url(#scene-blur${Math.min(i,2)})"`:''}>${animate?animate.replaceAll('PHOTO_INDEX',String(i)).replaceAll('PHOTO_DX',String(dx)).replaceAll('PHOTO_DY',String(dy)):''}<rect x="0" y="0" width="${pw}" height="${ph}" rx="8" fill="${p.card}" filter="url(#scene-photoShadow)"/><g clip-path="url(#${photoId})"><use href="#image-${f.thumb.replace(/[^a-z0-9]/gi,'')}" width="${pw}" height="${ph}"/></g><rect width="${pw}" height="${ph}" rx="8" stroke="#FFFFFF" stroke-opacity=".7" stroke-width="1.3" fill="none"/></g></g>`;
 }
 const tailX=l.bubble.tail[0],tailY=l.bubble.tail[1];
 const shape=`M18 0H${w-18}Q${w} 0 ${w} 18V${h-18}Q${w} ${h} ${w-18} ${h}H${tailX+30}L${tailX} ${tailY}L${tailX-8} ${h}H18Q0 ${h} 0 ${h-18}V18Q0 0 18 0Z`;
 return `<g id="bubble-${esc(id)}" pointer-events="none" opacity="${opacity}" transform="translate(${x} ${y+lift})"><g transform="scale(${scale})"><defs><clipPath id="glass-${esc(id)}"><path d="${shape}"/></clipPath></defs><path d="${shape}" fill="${p.bubble}" fill-opacity=".12" filter="url(#scene-bubbleShadow)"/><g clip-path="url(#glass-${esc(id)})"><use href="#scene-backdrop" transform="translate(${-x} ${-y})" filter="url(#scene-frost)" opacity=".76"/></g><path d="${shape}" fill="${p.bubble}" fill-opacity="${l.bubble.glass?.opacity??.36}" stroke="url(#scene-glassEdge)" stroke-width="1.1"/>${text(state.title,18,27,titleSize,p.purple,{maxWidth:w-36})}${text(ellipsis(state.subtitle,l.bubble.subtitle_size,w-36),18,43,l.bubble.subtitle_size,p.muted,{weight:400})}${photos}</g></g>`;
}
export function renderScene({profile,travel,layout:l,manifest,stats,map,theme='light',timeMs=0,animated=false,buildDate='1970-01-01',includeMap=true}){
 const p=palettes[theme],previews=selectPreviews(manifest,travel.preview,buildDate),frame=frameAt(timeMs,travel.preview,previews);
 const dur=previews.length*travel.preview.state_cycle_ms,initial=travel.preview.initial_idle_ms;
 const cycles=previews.map((s,index)=>({state:s,offset:index*travel.preview.state_cycle_ms}));
 function animSamples(index,fn){const times=new Set([0,dur]);for(const phase of Object.values(travel.preview.phases))for(const t of phase)times.add(index*travel.preview.state_cycle_ms+t);for(let t=0;t<travel.preview.state_cycle_ms;t+=150)times.add(index*travel.preview.state_cycle_ms+t);
  const ts=[...times].filter(t=>t<=dur).sort((a,b)=>a-b);return {keys:ts.map(t=>+(t/dur).toFixed(6)),values:ts.map(t=>{const f=frameAt(initial+(t===dur?dur-.001:t),travel.preview,previews);return fn(f.state?.code===previews[index].code?f:{opacity:0,highlight:0,spread:0,lift:10,scale:.96});})};}
 function cssAnimation(id,index,kind){const samples=animSamples(index,f=>kind==='opacity'?f.opacity:kind==='highlight'?f.highlight:f.spread);const name=`${kind}-${id}`;return `@keyframes ${name}{${samples.keys.map((k,i)=>`${k*100}%{opacity:${samples.values[i].toFixed(4)}}`).join('')}}#${id}{opacity:0;animation:${name} ${dur}ms linear ${initial}ms infinite;}`;}
 let styles='',defs='';const imageSet=new Map();for(const s of previews)for(const f of s.preview)imageSet.set(f.thumb,f);
 for(const [key,f] of imageSet){const id=`image-${key.replace(/[^a-z0-9]/gi,'')}`;defs+=`<image id="${id}" width="${l.bubble.photo[2]}" height="${l.bubble.photo[3]}" preserveAspectRatio="xMidYMid slice" href="${f.dataURI}"/>`;}
 for(const s of previews)s.preview.forEach((f,i)=>{defs+=`<clipPath id="photo-${s.code}-${i}"><rect width="${l.bubble.photo[2]}" height="${l.bubble.photo[3]}" rx="8"/></clipPath>`;});
 const header=text(profile.banner[0],600,75,l.fonts.banner,'#FFFFFF',{anchor:'middle',weight:700});
 const second=text(profile.banner[1],600,75,29,'#FFFFFF',{anchor:'middle',maxWidth:900});
 if(animated)styles+=`@keyframes typing-one{0%{clip-path:inset(0 100% 0 0)}17%,38%{clip-path:inset(0)}43%,100%{clip-path:inset(0 100% 0 0)}}@keyframes typing-two{0%,50%{clip-path:inset(0 100% 0 0)}73%,93%{clip-path:inset(0)}100%{clip-path:inset(0 100% 0 0)}}.greeting{animation:typing-one 8.8s linear infinite;transform-box:fill-box}.tagline{animation:typing-two 8.8s linear infinite;transform-box:fill-box;clip-path:inset(0 100% 0 0)}`;
 let content=`<rect width="${l.canvas.width}" height="${l.canvas.height}" fill="${p.bg}"/><g clip-path="url(#scene-bannerClip)"><rect width="1200" height="122" fill="url(#scene-bg)"/><circle cx="172" cy="29" r="65" fill="#fff" opacity=".055"/><circle cx="982" cy="27" r="87" fill="#F8DFFF" opacity=".07"/><g>${animated?transformed([[-35,0],[35,0],[-35,0]],[0,.5,1],10000):''}<path d="M-100 92C130 70 305 122 525 100C745 71 930 75 1300 102V135H-100Z" fill="url(#scene-waveA)"/></g><g>${animated?transformed([[30,0],[-30,0],[30,0]],[0,.5,1],13000):''}<path d="M-100 110C170 125 365 90 610 112C860 139 1050 96 1300 113V140H-100Z" fill="url(#scene-waveB)"/></g><circle cx="96" cy="37" r="2" fill="#fff" opacity=".45"/><circle cx="1070" cy="50" r="2.5" fill="#fff" opacity=".6"/><g filter="url(#scene-textGlow)"><g class="greeting">${header}</g>${animated?`<g class="tagline">${second}</g>`:''}</g></g>${clouds(theme,l,animated)}`;
 profile.about.forEach((s,i)=>{content+=text(s,600,149+i*27,l.fonts.about,i===1?p.purple:p.pink,{anchor:'middle',maxWidth:980});});
 const [sx,sy,sw,sh]=l.boxes.stats;content+=card(l.boxes.stats,p);
 const labels=['Total Stars Earned:','Total Commits (last year):','Total PRs:','Total Issues:','Contributed to (last year):'];const nums=[stats.stars,stats.commits,stats.prs,stats.issues,stats.contributed];
 labels.forEach((s,i)=>{const y=sy+32+i*29;content+=icon(i,sx+21,y-13,p)+text(s,sx+53,y,l.fonts.label,p.ink,{weight:600,family:'arimo'})+text(value(nums[i]),sx+239,y,l.fonts.number,p.ink,{anchor:'end',maxWidth:32,weight:600,family:'arimo'});});content+=rankRing(sx+330,sy+85,39,stats.rank,p);
 const [mx,my,mw,mh]=l.boxes.streak;content+=card(l.boxes.streak,p)+`<path d="M${mx+204} ${my+16}V${my+155}" stroke="${p.border}"/>`;
 content+=text(value(stats.total),mx+104,my+68,l.fonts.large,p.ink,{anchor:'middle',weight:700,family:'arimo'})+text('Total Contributions',mx+104,my+95,15,p.purple,{anchor:'middle',weight:600,family:'arimo'})+text(stats.created_at?`${fmtDate(stats.created_at)} – Present`:'— – Present',mx+104,my+124,13,p.muted,{anchor:'middle',weight:400,maxWidth:188,family:'arimo'});
 const cx=mx+284,cy=my+63,r=39;content+=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${p.track}" stroke-width="5"/><path d="M${cx-14} ${cy-36}A${r} ${r} 0 1 0 ${cx+14} ${cy-36}" fill="none" stroke="${p.pink}" stroke-width="5" stroke-linecap="round"/><path d="M0 25C-15 19 -11 9 -3 4C2 0 1 -5 0 -8C12 -1 7 5 12 9C18 2 18 14 16 18C14 25 7 27 5 24C10 18 6 14 3 12C5 19 -1 21 0 25Z" transform="translate(${cx-2} ${my+20}) scale(.7)" fill="${p.pink}"/>`+text(value(stats.streak?.count),cx,cy+11,33,p.ink,{anchor:'middle',weight:700,family:'arimo'})+text('Current Streak',cx,my+128,15,p.pink,{anchor:'middle',weight:600,family:'arimo'})+text(stats.streak?.start?`${fmtShort(stats.streak.start)} – ${fmtShort(stats.streak.end)}`:'—',cx,my+151,13,p.muted,{anchor:'middle',weight:400,family:'arimo'});
 const [tx,ty,tw,th]=l.boxes.travel;content+=card(l.boxes.travel,p)+text(travel.map.title,tx+14,ty+23,l.fonts.title,p.pink);
 if(includeMap){content+='<g clip-path="url(#scene-mapClip)">';for(const shape of map){const s=[...manifest.states,...(manifest.regions??[])].find(s=>s.code===shape.code),base=s.visited?s.color:(theme==='dark'?'#40394D':travel.map.unvisited_color);content+=`<path id="state-${s.code}" d="${shape.path}" fill="${base}" stroke="${theme==='dark'?p.border:travel.map.border_color}" stroke-width=".6"/>`;
  const index=previews.findIndex(s=>s.code===shape.code);if(index>=0){const opacity=frame.state?.code===s.code?frame.highlight:0;const id=`highlight-${s.code}`;if(animated)styles+=cssAnimation(id,index,'highlight');content+=`<g id="${id}" opacity="${opacity}" pointer-events="none"><path d="${shape.path}" fill="${travel.map.active_color}"/><circle cx="${shape.anchor[0]}" cy="${shape.anchor[1]}" r="4.2" fill="${p.purple}" stroke="#FFF" stroke-width="1.3"/></g>`;}}
 content+='</g>';}
 content+=text(travel.map.footer_template.replace('{visited}',manifest.visited),tx+tw/2,ty+164,13,p.muted,{anchor:'middle',weight:400,family:'arimo'});
 content=`<g id="scene-backdrop">${content}</g>`;
 for(const {state:s,offset} of cycles){const active=frame.state?.code===s.code,fr=active?frame:{opacity:0,spread:0,lift:10,scale:.96};let bubble=renderBubble({...s,anchor:map.find(m=>m.code===s.code).anchor},l,theme,{...fr,scale:animated?1:fr.scale,id:s.code,t:animated?undefined:fr.t,phases:travel.preview.phases});
  if(animated){
   const origin=bubbleOrigin(map.find(m=>m.code===s.code).anchor,l);const index=previews.indexOf(s),samples=animSamples(index,f=>f);
   const keyframes=(name,fn)=>`@keyframes ${name}{${samples.keys.map((k,i)=>`${k*100}%{${fn(samples.values[i])}}`).join('')}}`;
   styles+=keyframes(`float-${s.code}`,f=>`opacity:${f.opacity.toFixed(4)};transform:translate(${origin[0]}px,${(origin[1]+f.lift).toFixed(3)}px) scale(${f.scale.toFixed(4)});`)+`#bubble-${s.code}{opacity:0;animation:float-${s.code} ${dur}ms linear ${initial}ms infinite;}`;
   for(let i=1;i<s.preview.length;i++){
    const [dx,dy]=l.bubble.offsets[i]??[75,22],px=l.bubble.photo[0],py=l.bubble.photo[1],pid=`layer-${s.code}-${i}`;
    bubble=bubble.replace(`<g transform="translate(${px+dx*fr.spread} ${py+dy*fr.spread})">`,`<g id="${pid}" transform="translate(${px} ${py})">`);
    styles+=keyframes(`fan-${pid}`,f=>{const spread=f.opacity?layerSpread(f.t,travel.preview.phases,i):0;return `transform:translate(${(px+dx*spread).toFixed(3)}px,${(py+dy*spread).toFixed(3)}px) rotate(${(i*.8*spread).toFixed(3)}deg);`;})+`#${pid}{animation:fan-${pid} ${dur}ms linear ${initial}ms infinite;}`;
   }
  }
content+=bubble;
 }
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${l.canvas.width}" height="${l.canvas.height}" viewBox="0 0 ${l.canvas.width} ${l.canvas.height}" role="img"><title>${esc(profile.banner[0]+' — '+profile.about.join(' ')+' — GitHub statistics and US travel map')}</title><defs><linearGradient id="scene-bg" x2="1" y2="1"><stop stop-color="#89A4EB"/><stop offset=".48" stop-color="#A592ED"/><stop offset="1" stop-color="#C690E0"/></linearGradient><linearGradient id="scene-waveA"><stop stop-color="#FFFFFF" stop-opacity=".08"/><stop offset=".5" stop-color="#F5E8FF" stop-opacity=".27"/><stop offset="1" stop-color="#FFFFFF" stop-opacity=".08"/></linearGradient><linearGradient id="scene-waveB"><stop stop-color="#E9EEFF" stop-opacity=".2"/><stop offset="1" stop-color="#F5DDF8" stop-opacity=".27"/></linearGradient><clipPath id="scene-bannerClip"><rect width="1200" height="122" rx="17"/></clipPath><clipPath id="scene-mapClip"><rect x="${l.map.box[0]-2}" y="${l.map.box[1]-2}" width="${l.map.box[2]+4}" height="${l.map.box[3]+4}"/></clipPath><linearGradient id="scene-glassEdge" x2=".7" y2="1"><stop stop-color="#fff" stop-opacity=".7"/><stop offset=".5" stop-color="#D8C1EF" stop-opacity=".35"/><stop offset="1" stop-color="#C2A0DF" stop-opacity=".5"/></linearGradient><filter id="scene-frost"><feGaussianBlur stdDeviation="${l.bubble.glass?.background_blur??2.5}"/></filter><filter id="scene-textGlow" x="-.2" y="-.3" width="1.4" height="1.6"><feGaussianBlur stdDeviation="2" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><filter id="scene-cloudSoft"><feDropShadow dy="1" stdDeviation=".6" flood-color="#B9A8DD" flood-opacity=".11"/></filter><filter id="scene-bubbleShadow" x="-.15" y="-.15" width="1.35" height="1.4"><feDropShadow dy="5" stdDeviation="5" flood-color="#A17ECB" flood-opacity=".25"/></filter><filter id="scene-photoShadow"><feDropShadow dy="3" stdDeviation="3" flood-opacity=".15"/></filter><filter id="scene-blur1"><feGaussianBlur stdDeviation=".75"/></filter><filter id="scene-blur2"><feGaussianBlur stdDeviation="1.5"/></filter>${defs}</defs>${styles?`<style>${styles}</style>`:''}${content}</svg>`.replace(/[ \t]+$/gm,'');
}
