import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';import sharp from 'sharp';
const base='https://mikamikasuki.github.io/mikamikasuki/',repo='https://github.com/mikamikasuki/mikamikasuki'+(process.env.README_VERSION?'?v='+process.env.README_VERSION:'');const b=await chromium.launch();const p=await b.newPage({viewport:{width:1280,height:900}});const checks={},published=await(await p.request.get(base+'data.json')).json();
for(const theme of ['light','dark']){await p.emulateMedia({colorScheme:theme,reducedMotion:'no-preference'});await p.goto(repo,{waitUntil:'domcontentloaded'});const img=p.locator('article picture img').first();await img.evaluate(e=>e.decode());if(theme==='light'){
 const captures=[];for(let i=0;i<8;i++){if(i)await p.waitForTimeout(850);const bytes=await img.screenshot();captures.push(await sharp(bytes).resize(1200,404).extract({left:820,top:75,width:235,height:150}).raw().toBuffer());}
 const difference=(a,b)=>a.reduce((sum,n,i)=>sum+Math.abs(n-b[i]),0)/a.length;
 checks.motion={maxChange:Math.max(...captures.flatMap((a,i)=>captures.slice(i+1).map(b=>difference(a,b))))};assert.ok(checks.motion.maxChange>3);
}else await p.waitForTimeout(3000);const state=await img.evaluate(e=>({w:e.naturalWidth,h:e.naturalHeight,currentSrc:e.currentSrc,href:e.closest('a').href,source:[...e.closest('picture').querySelectorAll('source')].map(s=>({media:s.media,srcset:s.srcset,canonical:s.getAttribute('data-canonical-src'),matches:matchMedia(s.media).matches}))}));assert.equal(state.w,1200);assert.equal(state.h,published.layout.canvas.height);assert.equal(state.href,base);assert.ok(state.source.some(s=>s.media.includes('color-scheme: dark')));const selected=theme==='dark'?state.source.find(s=>s.matches):null;if(selected)assert.equal(selected.srcset,state.currentSrc);checks[theme]=state;await img.screenshot({path:`.test-output/github-production-${theme}.png`});}
await p.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await p.reload({waitUntil:'domcontentloaded'});const img=p.locator('article picture img').first();await img.evaluate(e=>e.decode());checks.reduced=await img.evaluate(e=>({currentSrc:e.currentSrc,matchingSource:[...e.closest('picture').querySelectorAll('source')].find(s=>matchMedia(s.media).matches)?.getAttribute('data-canonical-src')}));assert.ok(checks.reduced.matchingSource?.includes('profile-dark-static.svg'));await img.screenshot({path:'.test-output/github-production-reduced-dark.png'});await img.click();await p.waitForURL(base);checks.clickURL=p.url();
const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('#state-select option').nth(51).waitFor({state:'attached'});assert.equal(await p.locator('#state-select option').count(),52);await p.locator('#state-select').selectOption('CA');assert.equal(await p.locator('#photo-stack img').count(),3);const caCount=published.manifest.states.find(s=>s.code==='CA').photos.length;assert.equal(await p.locator('#bubble-photo-count').textContent(),`${caCount} ${caCount===1?'photo':'photos'}`);checks.production=await(await p.request.get(base+'data.json')).json();assert.equal(checks.production.manifest.visited,25);assert.equal(checks.production.travel.preview.state_cycle_ms,4000);assert.equal(checks.production.travel.preview.phases.exit[1],2000);assert.equal(checks.production.layout.bubble.readme_subtitle_size,10.5);for(const code of ['CA','NJ']){const state=checks.production.manifest.states.find(s=>s.code===code);assert.ok(state.photos.length>0);assert.equal(state.preview.length,3);assert.equal(state.preview.filter(f=>!f.sample).length,Math.min(3,state.photos.length));}assert.equal(checks.production.stats.status,'fresh');assert.deepEqual(errors,[]);await p.waitForTimeout(500);await p.screenshot({path:'.test-output/live-pages.png'});await p.keyboard.press('Escape');await p.clock.install();await p.clock.fastForward(75000);assert.equal(await p.locator('#bubble').isVisible(),false);
const r=await p.request.get(base+'assets/readme/profile-light.svg');assert.equal(r.status(),200);assert.ok(r.headers()['content-type'].includes('image/svg+xml'));checks.contentType=r.headers()['content-type'];const svg=await r.text();assert.ok(svg.includes('id="typing-caret"'));const visited=[...checks.production.manifest.states,...checks.production.manifest.regions].filter(s=>s.visited);checks.previewPlaces=visited.map(s=>s.code);checks.previewCycleMs=visited.length*checks.production.travel.preview.state_cycle_ms;assert.equal((svg.match(/id="bubble-[A-Z]{2}"/g)??[]).length,visited.length);for(const s of visited)assert.ok(svg.includes(`id="bubble-${s.code}"`));assert.ok(svg.includes(`${checks.previewCycleMs}ms`));assert.ok(!svg.includes('SAMPLE IMAGE'));
// Seek the actual GitHub image source to verify the one-shot intro separately
// from the repeating bubble; its screenshot region above excludes the cards.
const introPage=await b.newPage({reducedMotion:'no-preference',colorScheme:'light'}),camo=await introPage.request.get(checks.light.currentSrc);assert.equal(camo.status(),200);await introPage.setContent(await camo.text());
checks.entrance=await introPage.evaluate(()=>{
 const animations=document.getAnimations();for(const a of animations)a.pause();
 const seek=t=>{for(const a of animations)a.currentTime=t;};
 const read=()=>({rows:[...document.querySelectorAll('.scene-row-intro')].map(e=>+getComputedStyle(e).opacity),rings:[...document.querySelectorAll('#scene-rank-ring,#scene-streak-ring')].map(e=>({dash:parseFloat(getComputedStyle(e).strokeDasharray),opacity:+getComputedStyle(e).opacity,transform:getComputedStyle(e).transform})),zoom:getComputedStyle(document.querySelector('#scene-map-intro')).transform,states:[...document.querySelectorAll('path[id^="state-"].scene-card-intro')].map(e=>({code:e.id.slice(6),delay:parseFloat(getComputedStyle(e).animationDelay),duration:parseFloat(getComputedStyle(e).animationDuration),fill:getComputedStyle(e).fill,base:e.getAttribute('fill')}))});
 seek(0);const start=read();seek(320);const early=read();seek(1580);const end=read();return {start,early,end};
});
assert.deepEqual(checks.entrance.start.rows,[0,0,0,0,0]);assert.equal(checks.entrance.start.zoom,'matrix(1.08, 0, 0, 1.08, 0, 0)');assert.ok(checks.entrance.start.rings.every(r=>r.dash===0&&r.opacity===0));assert.ok(checks.entrance.early.rings.every((r,i)=>r.dash>0&&r.transform===checks.entrance.start.rings[i].transform));assert.equal(checks.entrance.end.zoom,'none');assert.deepEqual(checks.entrance.end.rows,[1,1,1,1,1]);assert.equal(checks.entrance.end.states.length,visited.length);
const wave=Object.fromEntries(checks.entrance.end.states.map(s=>[s.code,s]));for(const [a,b] of [['OH','PA'],['CO','SD'],['NV','ID']])assert.ok(wave[a].delay<wave[b].delay+wave[b].duration);for(const s of checks.entrance.end.states){assert.ok(s.delay+s.duration<=1.6);assert.equal(s.fill,'rgb('+[1,3,5].map(i=>parseInt(s.base.slice(i,i+2),16)).join(', ')+')');}
delete checks.production.map;await fs.writeFile('.test-output/live-checks.json',JSON.stringify(checks,null,2));await b.close();console.log('Live checks passed: GitHub light/dark/reduced image sources, published canvas dimensions, whole-image Pages link, live map/confirmed visits, fresh statistics, SVG Content-Type and one-shot card entrance.');
