import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import sharp from 'sharp';import {selectPreviews} from '../src/render/timeline.mjs';import {travelSchema,profileSchema} from '../src/content/schema.mjs';
const root='dist',data=JSON.parse(await fs.readFile(`${root}/data.json`));travelSchema.parse(data.travel);profileSchema.parse(data.profile);assert.equal(data.manifest.states.length,50);assert.equal(data.map.filter(s=>s.kind!=="district").length,50);assert.equal(data.manifest.visited,data.manifest.states.filter(s=>s.visited).length);const files=[];
async function walk(dir){for(const item of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())await walk(p);else files.push(p);}}await walk(root);
for(const p of files){if(/\.(json|html|svg|js|yaml)$/.test(p)){const s=await fs.readFile(p,'utf8');assert.ok(!/\/Users\/|github_pat_|ghp_[A-Za-z0-9]{20}|Synthetic photo fixture|visual-test fixture/.test(s),`Private/test content in ${p}`);if(p.endsWith('.svg')){assert.ok(!/<script|foreignObject|iframe|\son\w+=|href="https?:/i.test(s),`Unsafe SVG ${p}`);assert.ok(Buffer.byteLength(s)<4*1048576);for(const label of ['Total Stars Earned:','Total Commits (last year):','Total PRs:','Total Issues:','Contributed to (last year):','Total Contributions','Current Streak'])assert.ok(s.includes(label));if(p.includes('static'))assert.ok(!/<animate|<style/.test(s));}}
 if(p.endsWith('.webp')){const info=await sharp(p).metadata();assert.equal(info.exif,undefined);assert.equal(info.orientation,undefined);}
}
for(const s of [...data.manifest.states,...(data.manifest.regions??[])]){if(!s.visited)assert.equal(s.photos.length,0);for(const f of [...s.photos,...s.preview]){assert.ok(!f.src.includes('..'));await fs.access(path.join(root,f.src));await fs.access(path.join(root,f.thumb));}}
const selected=selectPreviews(data.manifest,data.travel.preview,data.manifest.build_date);assert.deepEqual(selected.map(s=>s.code).sort(),[...data.manifest.states,...data.manifest.regions].filter(s=>s.visited).map(s=>s.code).sort());
for(const theme of ['light','dark']){const svg=await fs.readFile(`${root}/assets/readme/profile-${theme}.svg`,'utf8');for(const s of selected)assert.ok(svg.includes(`id="bubble-${s.code}"`),`Missing ${s.code} in ${theme} preview`);assert.ok(svg.includes(`${selected.length*data.travel.preview.state_cycle_ms}ms`));}
console.log(`Production validation passed: ${files.length} files; ${data.manifest.visited} visited states; no test photos, private paths, executable SVG or image EXIF.`);
